### ISSUE TITLE
An improved mod customization (custom stickers, custom bf freeplay, and custom results screen)

### ISSUE THREAD

**Issue by eddyblightsmashcraft2605** [Psych-Slice/P-Slice#10]
### What feature do you want to get added on the **P-Slice** engine?

One thing I want you to include in the p-slice hotfixes is customization to certain things about v-slice

that is, the transition stickers, the freeplay bf (or almost the entire menu), and the results screen

This more than anything to perhaps give more essence to the engine, and more than anything to make it more customizable, since I tried to test the customized stickers in the p-slice and the engine crashed several times

Maybe in future updates they will add more customization and maybe make an improved modfolder

**Comment by mikolka9144** [comment]
Custom stickers is definitely something I want to add in 1.1

But I still want to balance any features from v-slice with existing Psych mods
