### ISSUE TITLE
Problem opening freeplay/question about certain game assets.

### ISSUE THREAD

**Issue by Sonicfan0208** [Psych-Slice/P-Slice#24]
### Describe your bug here.

So, the game decides to crash when I try to open the freeplay menu without the "base game" mod enabled, i've tried with other mods and it still crashes, I don't know if it is possible for you to do this but in a future update, can you put the files that are in the "base game" mod into the assets folder?

### Command Prompt/Terminal logs ()

```bash
no terminal log appears, i just had to fill this out
```

### Are you modding a build from source or with Lua?

No modding

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, I disabled the "Base game" mod in the mods menu.

**Comment by mikolka9144** [comment]
Outdated
