### ISSUE TITLE
Custom Freeplay Song Preview (like in little man 2)

### ISSUE THREAD

**Issue by insertnameuserhere** [Psych-Slice/P-Slice#25]
### What feature do you want to get added on the **P-Slice** engine?

while in freeplay it plays a different audio file called "inst-freeplay" while in playstate it plays the "inst" file that the song has

oh also if the "inst-freeplay" file does not exist it just uses the "inst" file instead

**Comment by insertnameuserhere** [comment]
like this
https://github.com/user-attachments/assets/9b636cda-309c-46e7-b3e1-86c002cbecca

**Comment by insertnameuserhere** [comment]
@mikolka9144

**Comment by mikolka9144** [comment]
I want to implement Freeplay song previews in a similar way the V-slice does that. There won't be any additional file, but I may add some functionality to define which part of the song to play as a preview.

Aug 18, 2024 8:56:58 PM insertnameuserhere ***@***.***>:
