### ISSUE TITLE
Freeplay Bf animation on failed json

### ISSUE THREAD

**Issue by Blocks-Games** [Psych-Slice/P-Slice#28]
### Describe your bug here.

I added my new song to the freeplay menu, and i forgot to set it to my custom difficulty. So when I went to play it. It made the error song but bf kept doing the animation when you play a song. This happened everytime I went to select another song

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes

**Comment by mikolka9144** [comment]
That one is kinda on your end, but exiting and entering freeplay again should fix this issue
