### ISSUE TITLE
Add a Hmm 

### ISSUE THREAD

**Issue by KaffeineMUSIC** [Psych-Slice/P-Slice#36]
### What feature do you want to get added on the **P-Slice** engine?

add a hmm to the source cause i cant build the game right due to the libs it asks for keeps breaking it

**Comment by mikolka9144** [comment]
I had too many issues with hmm, so won't be adding it.

For setup files for dependencies see [here](https://github.com/Psych-Slice/P-Slice/tree/master/setup)
