### ISSUE TITLE
PLEASE SUPPORT PSYCH ENGINE 0.7.3 FOR P-Slice ENGINE

### ISSUE THREAD

**Issue by DavesTheBone** [Psych-Slice/P-Slice#37]
### YES, I SAYD PLEASE SUPPORT PSYCH ENGINE 0.7.3 FOR P-Slice ENGINE

**Comment by mikolka9144** [comment]
Not happening. btw P-Slice 1.1 is on 0.7.3

**Comment by DavesTheBone** [comment]
oh ok
