### ISSUE TITLE
Hold Cover(Customizable Skin) & Funkin' Preloader & Moved V-Slice options to right place & README rewrite

### ISSUE THREAD

**Issue by soushimiya** [Psych-Slice/P-Slice#38]
### What feature do you want to get added on the **P-Slice** engine?

For some reason only contributors can create PRs, so I'll put it here.

Added Hold Cover and Funkin' Preloader(Now it has real font from V-Slice).
Also i think it's redundant to have the V-Slice option in a separate category so I've moved it to the correct place.
Rewritten README

Most of the work has already been done (the hold cover is still unstable).
https://github.com/soushimiya/P-Slice-PullReq-again

**Comment by mcagabe19** [comment]
and also sustain notes are not right, they're little too much

**Comment by mcagabe19** [comment]
oh yeah and camera events aswell

**Comment by mikolka9144** [comment]
That readme document is so much cleaner, that what I wrote in the hurry before.

Definitely cherr-picking those commits (with credit obviously)

**Comment by mikolka9144** [comment]
@soushimiya feel free to send over link to your gb account (if you have one)

**Comment by soushimiya** [comment]
I'm currently rewriting the Hold Cover code, so I'll let you know when it's done.

**Comment by mcagabe19** [comment]
everything is at p-slice dev now so that issue can be closed
