### ISSUE TITLE
FreeplayState capules being horrible on low fps

### ISSUE THREAD

**Issue by mcagabe19** [Psych-Slice/P-Slice#39]
### Describe your bug here.

the title and I'm doing mobile port btw but I also tested on low fps in my laptop it does the same thing

https://github.com/user-attachments/assets/ce0a4750-fa0c-44c0-9a05-3d942c006b7d

### Are you modding a build from source or with Lua?

No modding

### What is your build target?

Neko, HashLink, or other build system

### Did you edit anything in this build? If so, mention or summarize your changes.

No, I didn't

**Comment by mikolka9144** [comment]
I was able to fix it in an upcoming release
