### ISSUE TITLE
TUREEN'S QOL FUNCTIONS

### ISSUE THREAD

**Issue by TureenOfficial** [Psych-Slice/P-Slice#40]
- custom freeplay difficulty sprites, seperate from story mode difficulty sprites 

you could do this by reading for a difficulty name (eg. hard) with the prefix of "freeplay" in "images/freeplay"

- customisable stage editor hotkey in options

- the opportunity for hidden songs to only be visible AFTER completion (WITHOUT SOURCE) 

you could do this by making a new array called dependencies, with the song name, it reads if you've completed it yet and if you havent its hidden from menus

- midsong stage change event that swaps the currently active json (value 1) with the stage json you WANT to be active (value 2)

- weekName variable in the week.json should be whats loaded in the freeplay panel's details under the song name where it says "WEEK (week number)"

- you should be able to add **ALBUM COVER ART** as well as the **SONG RATINGS WITH STARS** underneath, 

On the side of the screen, these album covers would be within a folder, mods/images/freeplay/albumart, where you would add whatever image name you want. then, in the week.json, there should be another variable called album, where you would enter the image name, if it returns null, it should become the placeholder art from the base game!!

The stars underneath would just correspond to the song rating on the freeplay panel where it tells you the difficulty rating on the right side!!!

Thanks for reading, may add more soon
Tureen

**Comment by mikolka9144** [comment]
1. Good idea. I didn't though about addit it as a moddable feature, but would make for a great addition.
2. *I couldn't care less about the stage editor*
3. I think you could do that with existing system for locking weeks, but I'll not make anything explicit for it
4. "Can be done in Lua"
5. Awaits for merge
6. No.

**Comment by mikolka9144** [comment]
Closing because someone else suggested custom Freeplay graphics already

**Comment by TureenOfficial** [comment]
> Closing because someone else suggested custom Freeplay graphics already


yeah. it was me.
