### ISSUE TITLE
what is funkin.vis and how do i get it

### ISSUE THREAD

**Issue by DGEDom** [Psych-Slice/P-Slice#41]
### Describe your bug here.

funkin.vis - what the fuck is that

### Command Prompt/Terminal logs ()

```bash
Error: Could not find haxelib "funkin.vis", does it need to be installed?
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by TureenOfficial** [comment]
go to setup/
look for windows.bat
install everything from the bat file

**Comment by mikolka9144** [comment]
funkin.vis is a visualiser used by Nene's ABot to display cool bars. It should be installed by the setup script
