### ISSUE TITLE
Game says the engine is outdated, and asking me to update to P-Slice Engine 2.0 But I'm already on P-Slice Engine 2.0

### ISSUE THREAD

**Issue by sirGaius7** [Psych-Slice/P-Slice#42]
### Describe your bug here.

![Screenshot 2024-10-19 153117](https://github.com/user-attachments/assets/9a2149c0-c10e-4e04-8065-9080d974f8b5)
![Screenshot 2024-10-19 153132](https://github.com/user-attachments/assets/198f3d91-005d-4082-870c-24223dc52302)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mikolka9144** [comment]
I updated the 1.0 version
