### ISSUE TITLE
Freeplay assets dissapearing

### ISSUE THREAD

**Issue by DrebDaDev** [Psych-Slice/P-Slice#46]
### Describe your bug here.

Im working on a custom character and it all works but i have an issue, whenever i enter and exit a song the virtual numbers and the bg completely dissapear
before entering a song
![image](https://github.com/user-attachments/assets/a6b671a0-75b5-4635-bbc0-510b824164fa)
after entering a song
![image](https://github.com/user-attachments/assets/da3702b5-8374-4399-8850-4d260199c3af)

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

copied and modified bf's character data

**Comment by mikolka9144** [comment]
Fixed in2.0.1
