### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by DavidHyena28** [Psych-Slice/P-Slice#47]
### Describe your bug here.

i tried to compile p-slice 2.0 (0.6.3) but got these errors

### Command Prompt/Terminal logs ()

```bash
source/mikolka/stages/misc/AtlasLoader.hx:72: characters 7-18 : flxanimate.FlxAnimate has no field loadAtlasEx (Suggestion: loadAtlas)
C:/HaxeToolkit/haxe/lib/flixel-ui/2,5,0/flixel/addons/ui/FlxUICursor.hx:564: characters 9-11 : Warning : Potential typo detected (expected similar values are flixel.addons.ui.SortMethod.ID)
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Nop

**Comment by mikolka9144** [comment]
Wrong version if FlxAnimate?
Try running ```haxelib git flxanimate https://github.com/Psych-Slice/FlxAnimate.git pslice-dev```

**Comment by mikolka9144** [comment]
or you're missing ```import flxanimate.PsychFlxAnimate as FlxAnimate;``` (it should be located in source/import.hx)
