### ISSUE TITLE
Erect Is Missing, But Its In The Files

### ISSUE THREAD

**Issue by H1nataDev** [Psych-Slice/P-Slice#49]
### Describe your bug here.

I Were Trying To Test This Engine, So I Was Going To My Favorite Songs, Erect, But Theres No Erect In Freeplay, But WHen I Checked It Is In The Files

### Command Prompt/Terminal logs ()

```bash
a
```

### Are you modding a build from source or with Lua?

No modding

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mikolka9144** [comment]
Have you try changing the difficulty on "random" capsule?

**Comment by H1nataDev** [comment]
It Worked

**Comment by H1nataDev** [comment]
But It Shows "Week 8", Or  "Week 13" And Its Strange

**Comment by mikolka9144** [comment]
Because they're separate weeks because of how psych works
