### ISSUE TITLE
How do I add custom playable characters

### ISSUE THREAD

**Issue by hops678** [Psych-Slice/P-Slice#51]
### What is your question?

I can't figure out how to add the custom playable characters to the character select screen, Can you help me

**Comment by mikolka9144** [comment]
I'm planing to write a proper wiki explaining it quite soon

**Comment by mcagabe19** [comment]
wiki does exists now I think so that can be closed
https://github.com/Psych-Slice/P-Slice/wiki/Custom-Characters

**Comment by hops678** [comment]
thankyou
