### ISSUE TITLE
A mac port

### ISSUE THREAD

**Issue by mllso824** [Psych-Slice/P-Slice#54]
### What feature do you want to get added on the **P-Slice** engine?

You had the time to add a linux port why not add a mac port it will make it easier for people to play!

**Comment by mikolka9144** [comment]
1. I don't have a Mac to properly test
2. Here is Mac version: https://github.com/Psych-Slice/P-Slice/actions/runs/11420650132

**Comment by mllso824** [comment]
Thanks!
