### ISSUE TITLE
How do I make spookyMansionErect type characters?

### ISSUE THREAD

**Issue by ThatJanWTM** [Psych-Slice/P-Slice#55]
### What is your question?

How do I make characters that are affected by the lightning in spookyMansionErect?

![screenshot-2024-11-01-17-20-53](https://github.com/user-attachments/assets/fc6a5f8b-bc56-4e33-8cd2-7990196c06f7)

I tried to make a dark version of the character but when lightning strikes it still displays BF and GF

**Comment by mikolka9144** [comment]
That stage wasn't ever meant to be modded, but you could in your mod replace the shadow characters with your own.

**Comment by ThatJanWTM** [comment]
by replace the shadow characters you mean the bf_dark sprite sheet itself or the BOYFRIEND sprite sheet??
