### ISSUE TITLE
Fallo visual

### ISSUE THREAD

**Issue by DibujosCreativos** [Psych-Slice/P-Slice#56]
### Describe your bug here.

![image](https://github.com/user-attachments/assets/4cd71bde-f089-41a3-b8bd-2c35b5f03ca3)
![image](https://github.com/user-attachments/assets/196de68a-1c6d-40b6-a3d9-f8c898d81a25)
![image](https://github.com/user-attachments/assets/d3a0f077-ed57-41d7-86f2-a29b9be17639)
When entering the character change, the square indicating the character is located in a position far from normal (3 examples).

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Yes, but I only added one more character and this problem happens to all of them (BF and Pico).

**Comment by DibujosCreativos** [comment]
This only happens in the compiler version, as this does not happen in the gamebanana version.

**Comment by mikolka9144** [comment]
iirc that's just the way it works. Since you're modding from source, you _should_ be able to change this behavior
