### ISSUE TITLE
I think the results are not correct

### ISSUE THREAD

**Issue by DibujosCreativos** [Psych-Slice/P-Slice#58]
### Describe your bug here.

![image](https://github.com/user-attachments/assets/54124ea5-d00a-4650-b70d-263de5dd9a88)
I think there is a bug here, I got 86% and it sends me to the perfect result.

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by a-random441** [comment]
thats because you fc'ed it

**Comment by moxie-coder** [comment]
> thats because you fc'ed it (the results screen is based on how many misses the player has)

have you ever considered trying that in V slice 0.5.2? Because I’m sure you haven’t, the animation is based on the *percentage*, not the misses

**Comment by mikolka9144** [comment]
You FC'ed a song. Rating is based on accuracy, but getting FC overrides it to always give "perfect"
