### ISSUE TITLE
How do I remove everything related to mobile?

### ISSUE THREAD

**Issue by DibujosCreativos** [Psych-Slice/P-Slice#65]
### What is your question?

Don't you think they should make a repository for those who only want to compile on PC and another one for mobiles?

**Comment by DibujosCreativos** [comment]
and if not, how do I remove everything related to mobiles for PC compilation?

**Comment by mikolka9144** [comment]
Everything related to mobile should be excluded on compilation for PC platforms. 

And touchscreen buttons can be hidden (and are on PC)

**Comment by mikolka9144** [comment]
@mcagabe19 I'll make a flag to exclude mobile support for desktop platforms

**Comment by mcagabe19** [comment]
we can't make a flag through, as I said mobile lua functions will be broken just leave as is and mobileC alpha 0, it doesn't disturb at all

**Comment by mikolka9144** [comment]
There's now a flag to compile without a mobile support, so I'll close this
