### ISSUE TITLE
Backing cards

### ISSUE THREAD

**Issue by ItzKony** [Psych-Slice/P-Slice#66]
### What is your question?

I'm trying to port Spooky Mix into P-Slice, but I dont know how to change or add the backing cards. Can someone help me?

**Comment by ItzKony** [comment]
![IMG_20241104_163100.jpg](https://github.com/user-attachments/assets/4a53870c-8e11-4ed3-83e3-f5257fad0df0)

**Comment by mcagabe19** [comment]
https://github.com/Psych-Slice/P-Slice/wiki/Metadata

**Comment by ItzKony** [comment]
> https://github.com/Psych-Slice/P-Slice/wiki/Metadata

It's not for the backing cards?

**Comment by mikolka9144** [comment]
There is no support for custom cards as of now

**Comment by ItzKony** [comment]
> There is no support for custom cards as of now

Oh okay ://
