### ISSUE TITLE
Question - How, Do I Use The Shaders For The Erect Backgrounds?

### ISSUE THREAD

**Issue by CatGamer99** [Psych-Slice/P-Slice#67]
### What is your question?

How, Do I Use The Shaders For The Erect Backgrounds? (FOR MY MOD) Cause, I Looked Into The Erect Stages JSONS, Data, ETC, And I Can't Find The Shader Codes For The Background.

**Comment by mikolka9144** [comment]
Here https://github.com/Psych-Slice/P-Slice/tree/master/source/shaders

With a bit of HScript magic you should be able to use them

**Comment by CatGamer99** [comment]
This, Works With 0.6.3 As Well?

**Comment by CatGamer99** [comment]
Ah, Ok Thanks Miko -CatGamerr (AKA The Creator Of Swaga Engine)
