### ISSUE TITLE
limo erect  stage wont work

### ISSUE THREAD

**Issue by DaveCharts** [Psych-Slice/P-Slice#68]
### Describe your bug here.

idk what happened but anytime i try to play a song with the limo erect stage, the game gets an error and i cant do anything about it
![Screenshot 2024-11-07 172925](https://github.com/user-attachments/assets/e1c3173b-02ff-4f71-974f-7e98da2425be)

### Command Prompt/Terminal logs ()

```bash
crash log thingy: Uncaught Error: Null Object Reference
In file mikolka/stages/erect/LimoRideErect.hx: CLS:LimoRideErect:createPost()  Line:181
In file states/PlayState.hx: CLS:PlayState:create()  Line:655
In file backend/MusicBeatState.hx: CLS:MusicBeatState:stagesFunc()  Line:206
In file states/PlayState.hx: CLS:PlayState:create()  Line:655
In file flixel/FlxGame.hx: CLS:FlxGame:switchState()  Line:639
In file flixel/FlxGame.hx: CLS:FlxGame:update()  Line:726
In file flixel/FlxGame.hx: CLS:FlxGame:step()  Line:679
In file flixel/FlxGame.hx: CLS:FlxGame:onEnterFrame()  Line:552
In file openfl/events/EventDispatcher.hx: CLS:EventDispatcher:__dispatchEvent()  Line:426
In file openfl/display/DisplayObject.hx: CLS:DisplayObject:__dispatch()  Line:1398
----------
Active mod: 
Platform: Windows


Please report this error to the GitHub page: https://github.com/mikolka9144/P-Slice

> Crash Handler written by: sqirra-rng
```

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

yes, added a few songs.

**Comment by mikolka9144** [comment]
From what I see you've set this stage on a custom song. You must set a directory in a week Json file for it to properly pull assets
