### ISSUE TITLE
V-slice to psych chart converter

### ISSUE THREAD

**Issue by Bfjfjvjnc** [Psych-Slice/P-Slice#75]
### What feature do you want to get added on the **P-Slice** engine?

You should add a V-slice to psych chart converter on the chart editot

**Comment by ThatJanWTM** [comment]
![image](https://github.com/user-attachments/assets/b352ae62-7b89-4725-948c-6e11852823a1)

**Comment by Bfjfjvjnc** [comment]
> ![image](https://private-user-images.githubusercontent.com/114443552/385096684-b352ae62-7b89-4725-948c-6e11852823a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNzM2NDksIm5iZiI6MTczMTM3MzM0OSwicGF0aCI6Ii8xMTQ0NDM1NTIvMzg1MDk2Njg0LWIzNTJhZTYyLTdiODktNDcyNS05NDhjLTZlMTE4NTI4MjNhMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMlQwMTAyMjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjAxYzBhYTZjMmJmNTMxMjZmOGJhMTU1MzZlMDY2MWJkNWMwZWIyZDI0MWRmY2UzOTE3YTdkOWU5Nzg4ZjZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.fLV9oCbh-V2-8ggVS6WL-7dlYP0WVhIuuIXdLX4C57U)

Is that on pslice android

**Comment by mcagabe19** [comment]
base psych and p-slice android doesn't have converters or open charts
