### ISSUE TITLE
W/S moving conductor not continuously 

### ISSUE THREAD

**Issue by fffdsfdsfds** [Psych-Slice/P-Slice#78]
### Describe your bug here.

https://github.com/user-attachments/assets/227a83f4-a71d-4a2d-8acc-4b88424cd371

### Are you modding a build from source or with Lua?

Lua

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by moxie-coder** [comment]
have you ever tried Shift + W/S?

**Comment by mikolka9144** [comment]
#76
