### ISSUE TITLE
Difficulties

### ISSUE THREAD

**Issue by UnderFellSansRed2** [Psych-Slice/P-Slice#86]
### Describe your bug here.

In the songs in Freeplay they don't let you change to erect or nightmare, only in the random section, it would be great if you could change it in the other songs sections

### Are you modding a build from source or with Lua?

No modding

### What is your build target?

Android

### Did you edit anything in this build? If so, mention or summarize your changes.

No

**Comment by mikolka9144** [comment]
Not a bug, just a psych quirk.

I didn't want to overcomplicate freeplay's song loading and that's the best I came up with.

TLDR: too much work to fix such a minor issue.
