### ISSUE TITLE
Crashes on char select, backing freeplay

### ISSUE THREAD

**Issue by 2JENO** [Psych-Slice/P-Slice#92]
### Describe your bug here.

![image](https://github.com/user-attachments/assets/0218fbf3-1b82-4aba-91d2-96b05d6d7200)

### Command Prompt/Terminal logs (required)

```bash
DJBoyfriend.hx:484: Successfully applied offset (boyfriend dj intro): 631.7, 362.6
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

Renamed "mikolka" to "pslice" and using psych 1.0 fork

**Comment by mikolka9144** [comment]
Are you sure that's P-Slice?

**Comment by 2JENO** [comment]
i think its happen on sticker sub state

**Comment by 2JENO** [comment]
found its happening on MusicBeatSubState

**Comment by 2JENO** [comment]
if i write this:
public function startQuadBatch(graphic:FlxGraphic, colored:Bool, hasColorOffsets:Bool = false, ?blend:BlendMode, smooth:Bool = false, ?shader:FlxShader)
	{
		#if FLX_RENDER_TRIANGLE
		return startTrianglesBatch(graphic, smooth, colored, blend);
		#else
		var itemToReturn = null;
		var blendInt:Int = FlxDrawBaseItem.blendToInt(blend);

		if (_currentDrawItem != null
			&& _currentDrawItem.type == FlxDrawItemType.TILES
			&& _headTiles.graphics == graphic
			&& _headTiles.colored == colored
			&& _headTiles.hasColorOffsets == hasColorOffsets
			&& _headTiles.blending == blendInt
			&& _headTiles.blend == blend
			&& _headTiles.antialiasing == smooth
			&& _headTiles.shader == shader)
		{
			return _headTiles;
		}

		if (_storageTilesHead != null)
		{
			itemToReturn = _storageTilesHead;
			var newHead = _storageTilesHead.nextTyped;
			itemToReturn.reset();
			_storageTilesHead = newHead;
		}
		else
		{
			itemToReturn = new FlxDrawItem();
		}
		
		if (graphic.isDestroyed) throw 'Attempted to queue an invalid FlxDrawItem, did you destroy a cached sprite?';

		itemToReturn.graphics = graphic;
		itemToReturn.antialiasing = smooth;
		itemToReturn.colored = colored;
		itemToReturn.hasColorOffsets = hasColorOffsets;
		itemToReturn.blending = blendInt;
		itemToReturn.blend = blend;
		itemToReturn.shader = shader;

		itemToReturn.nextTyped = _headTiles;
		_headTiles = itemToReturn;

		if (_headOfDrawStack == null)
		{
			_headOfDrawStack = itemToReturn;
		}

		if (_currentDrawItem != null)
		{
			_currentDrawItem.next = itemToReturn;
		}

		_currentDrawItem = itemToReturn;

		return itemToReturn;
		#end
	}

![image](https://github.com/user-attachments/assets/604bbcf4-af0a-4bd3-8e32-e04cb5259083)

**Comment by mikolka9144** [comment]
Not a P-Slice issue
