### ISSUE TITLE
Results broken (+ fix cuzim too lazy to make a pr)

### ISSUE THREAD

**Issue by sphis-Sinco** [Psych-Slice/P-Slice#97]
### Describe your bug here.

Ive started making mods with Pslice and I played a mod made with pSlice
and the vslice results have been weird.
getting a 80% gives a 100% results screen.

and ive fixed it!

the issue:
![Screenshot 2024-11-30 191845](https://github.com/user-attachments/assets/c43fa2a3-646a-47fe-a3e8-538f73f5693f)

replace it with this...
```hx
totalNotesHit += 1;
```
and its fixed!

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

I made a full scale mod and so have others

**Comment by Bfjfjvjnc** [comment]
Where do I fix this on I can't find the hx

**Comment by sphis-Sinco** [comment]
> Where do I fix this on I can't find the hx

PlayState.hx

do `ctrl + F` to find `totalNotesHit += daRating.ratingMod`
and replace `daRating.ratingMod` with `1`
